# fly.toml app configuration file generated for hidden-lake-6102 on 2023-09-21T10:19:21-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hidden-lake-6102"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
